service: bike-to-work-bot
tenant: personal
app: bike-to-work-daily
  
custom:
  stage: ${opt:stage, self:provider.stage} # shortcut for current stage

provider:
  name: aws
  credentials: ${secrets:aws-creds}
  runtime: python3.6
  stage: dev
  region: us-east-1
  # allow use of ${AWS::blah} CFN syntax
  variableSyntax: "\\${((?!AWS)[ ~:a-zA-Z0-9._'\",\\-\\/\\(\\)]+?)}"

  iamRoleStatements:
    - Effect: Allow
      Action: ssm:GetParameters
      Resource: arn:aws:ssm:us-east-1:704903784842:parameter/bike2workbot/*
    - Effect: Allow
      Action:  kms:Decrypt
      Resource:  arn:aws:kms:us-east-1:704903784842:key/bdf6fdbd-3928-44ae-9c1c-50cbbcb736ac 


  environment:
    STAGE: ${self:custom.stage}

package:
  include:
    - handler.py
  exclude:
    - '**/*'

plugins:
  - serverless-python-requirements
  - '@serverless/enterprise-plugin'

functions:
  tweet:
    handler: handler.tweet
    events:
      - schedule: cron(0 16 ? * MON-FRI *)
