# This is a basic workflow to help you get started with Actions

name: deploy
on:
  push:
    branches: [ master ]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - uses: actions/setup-python@v1
    - name: Install Serverless
      run: npm i -g serverless
    - name: Install Deps
      run: npm i
    - name: Deploy
      run: sls deploy
      
